name: "[internal] ttnn stress tests impl"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 45
      docker-image:
        required: true
        type: string
      build-artifact-name:
        required: true
        type: string
      wheel-artifact-name:
        required: true
        type: string

jobs:
  ttnn:
    name: ttnn stress tests ${{ inputs.arch }} ${{ inputs.runner-label }}
    runs-on:
      - "in-service"
      - "${{ inputs.runner-label }}"
      - "${{ (inputs.runner-label == 'config-tg' || inputs.runner-label == 'topology-6u') && 'bare-metal' || 'cloud-virtual-machine' }}"
    env:
      ARCH_NAME: ${{ inputs.arch }}
      LOGURU_LEVEL: INFO
      PYTHONPATH: ${{ github.workspace }}
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    defaults:
      run:
        shell: bash
    steps:
      - name: ⬇️  Setup Job
        uses: tenstorrent/tt-metal/.github/actions/setup-job@williamly/bh-qb-test
        timeout-minutes: 10
        with:
          wheel-artifact-name: ${{ inputs.wheel-artifact-name }}
          path: ${{ github.workspace }}

      - name: Run Stress Tests
        timeout-minutes: ${{ inputs.timeout }}
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          pytest tests/ttnn/stress_tests/

      # - uses: tenstorrent/tt-metal/.github/actions/cleanup@main
      #   if: always()
      #   with:
      #     path: ${{ github.workspace }}
