name: "[internal] UMD Unit tests"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 15
      docker-image:
        required: true
        type: string
      build-artifact-name:
        required: true
        type: string

jobs:
  umd-unit-tests:
    name: UMD tests ${{ inputs.arch }} ${{ inputs.runner-label }}
    runs-on:
      - ${{ inputs.runner-label }}
      - cloud-virtual-machine
      - in-service
    env:
      ARCH_NAME: ${{ inputs.arch }}
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
      LOGURU_LEVEL: INFO
      PYTHONPATH: ${{ github.workspace }}
    defaults:
      run:
        shell: bash
    steps:
      - name: ⬇️  Setup Job
        uses: tenstorrent/tt-metal/.github/actions/setup-job@williamly/bh-qb-test
        timeout-minutes: 10
        with:
          build-artifact-name: ${{ inputs.build-artifact-name }}
          path: ${{ github.workspace }}
      - name: Run UMD unit tests
        timeout-minutes: ${{ inputs.timeout }}
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          build/test/umd/${{ inputs.arch }}/unit_tests
